package com.example.ContactManagementApi.Entity;

import com.example.ContactManagementApi.Enum.RoleEnum;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * The Role class represents an entity for managing user roles in the
 * application. It contains fields for the role's unique identifier and the
 * role's name as an enumeration. This entity is mapped to a database table by
 * the JPA framework using the @Entity annotation.
 */
@Entity
public class Role {

	/**
	 * The unique identifier for each role entry. It is auto-generated by the
	 * database using the IDENTITY strategy.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * The name of the role, represented as an enum. The enum values are stored as
	 * strings in the database.
	 */
	@Enumerated(EnumType.STRING)
	private RoleEnum name;

	// Getters and Setters

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public RoleEnum getName() {
		return name;
	}

	public void setName(RoleEnum name) {
		this.name = name;
	}

}
